local Players,TweenService,UserInputService=game:GetService("Players"),game:GetService("TweenService"),game:GetService("UserInputService")
local p,pg=Players.LocalPlayer,Players.LocalPlayer:WaitForChild("PlayerGui")
local ci=function(c,props,parent)local o=Instance.new(c)for k,v in pairs(props or {})do o[k]=v end if parent then o.Parent=parent end return o end
local sg=ci("ScreenGui",{Name="StatsViewer",ResetOnSpawn=false,Enabled=false},pg)
local mf=ci("Frame",{Size=UDim2.new(0,350,0,350),Position=UDim2.new(0,20,0,20),BackgroundColor3=Color3.fromRGB(30,30,30),BackgroundTransparency=0.2,BorderSizePixel=2,BorderColor3=Color3.fromRGB(255,170,0)},sg)
local hf=ci("Frame",{Size=UDim2.new(1,-10,0,100),Position=UDim2.new(0,5,0,5),BackgroundTransparency=1},mf)
local tl=ci("TextLabel",{Size=UDim2.new(1,0,0,30),Position=UDim2.new(0,0,0,0),BackgroundTransparency=1,TextColor3=Color3.new(1,1,1),Font=Enum.Font.GothamBold,TextScaled=true,Text="⚔ Total Stats: 0"},hf)
local rl=ci("TextLabel",{Size=UDim2.new(1,0,0,30),Position=UDim2.new(0,0,0,35),BackgroundTransparency=1,TextColor3=Color3.new(1,1,1),Font=Enum.Font.GothamBold,TextScaled=true,Text="⭐ Rank: ???"},hf)
local nrl=ci("TextLabel",{Size=UDim2.new(1,0,0,30),Position=UDim2.new(0,0,0,70),BackgroundTransparency=1,TextColor3=Color3.new(1,1,1),Font=Enum.Font.GothamBold,TextScaled=true,Text="↓ Next Rank: 0"},hf)
local sf=ci("Frame",{Size=UDim2.new(1,-10,1,-110),Position=UDim2.new(0,5,0,105),BackgroundTransparency=1},mf); ci("UIListLayout",{FillDirection=Enum.FillDirection.Vertical,SortOrder=Enum.SortOrder.LayoutOrder,Padding=UDim.new(0,5)},sf)
local stats,icons,rows={"STR","DUR","ST","AG","BS"},{STR="⚔",DUR="🛡",ST="✊",AG="🏃",BS="🔥"},{}
for _,s in ipairs(stats) do local r=ci("Frame",{Size=UDim2.new(1,0,0,40),BackgroundTransparency=1},sf) rows[s]={main=ci("TextLabel",{Size=UDim2.new(0.5,-5,1,0),Position=UDim2.new(0,0,0,0),BackgroundTransparency=1,TextColor3=Color3.new(1,1,1),Font=Enum.Font.GothamBold,TextScaled=true,TextXAlignment=Enum.TextXAlignment.Left,Text=icons[s].." 0 (---)"},r), sub=ci("TextLabel",{Size=UDim2.new(0.5,-5,1,0),Position=UDim2.new(0.5,5,0,0),BackgroundTransparency=1,TextColor3=Color3.fromRGB(200,200,200),Font=Enum.Font.Gotham,TextScaled=true,TextXAlignment=Enum.TextXAlignment.Left,Text="(0) > ---"},r)} end
local ranks={{"F-",0},{"F",26},{"F+",51},{"E-",76},{"E",126},{"E+",176},{"D-",226},{"D",326},{"D+",426},{"C-",526},{"C",726},{"C+",926},{"B-",1126},{"B",1426},{"B+",1726},{"A-",2026},{"A",2751},{"A+",3476},{"S-",4201},{"S",5201},{"S+",6201},{"SS-",7201},{"SS",8701},{"SS+",10001},{"SSS-",12501},{"SSS",15001},{"SSS+",17501},{"X-",20001},{"X",24001},{"X+",28000},{"XX-",32001},{"XX",38001},{"XX+",44001},{"XXX-",50001},{"XXX",60001},{"XXX+",70001},{"Z-",80001},{"Z",95000},{"Z+",110001},{"ZZ-",125001},{"ZZ",145001},{"ZZ+",165001},{"ZZZ-",185001},{"ZZZ",210001},{"ZZZ+",235001},{"?",260000},{"??",500001},{"???",750000}}
local ps,pt={STR=0,DUR=0,ST=0,AG=0,BS=0},0
local function getRank(val)local c,n,d="F-","F",math.huge; for _,t in ipairs(ranks) do if val>=t[2] then c=t[1] else n=t[1]; d=t[2]-val; break end end return c,n,d end
local function getVal(s)local h=pg:FindFirstChild("HUD") and pg.HUD:FindFirstChild("Tabs") and pg.HUD.Tabs:FindFirstChild("StatsChecker") if h then local f=h:FindFirstChild(s) if f then local a=f:FindFirstChild("AMT") return a and tonumber(a.Text) or 0 end end return 0 end
local function tot() local t=0; for _,s in ipairs(stats) do t=t+getVal(s) end return t end
local function fmt(n)return (n==math.floor(n)) and ("+"..n) or ((n*10)==math.floor(n*10)) and string.format("+%.1f",n) or string.format("+%.2f",n) end
local tweens={}
local function playE(lbl)local orig=lbl.TextColor3; local i=TweenInfo.new(0.2,Enum.EasingStyle.Quad,Enum.EasingDirection.Out) local up=TweenService:Create(lbl,i,{TextColor3=Color3.fromRGB(0,255,0)}) local down=TweenService:Create(lbl,i,{TextColor3=orig}) if tweens[lbl] then tweens[lbl]:Cancel() end; tweens[lbl]=up; up:Play(); up.Completed:Connect(function() tweens[lbl]=down; down:Play(); down.Completed:Connect(function() tweens[lbl]=nil end) end) end
local function showInc(lbl,n)local eff=ci("TextLabel",{Size=lbl.Size,Position=lbl.Position,BackgroundTransparency=1,Text=fmt(n),Font=lbl.Font,TextScaled=lbl.TextScaled,TextColor3=Color3.fromRGB(0,255,0),ZIndex=lbl.ZIndex+1},lbl.Parent) local i=TweenInfo.new(1,Enum.EasingStyle.Quad,Enum.EasingDirection.Out) local goal={Position=eff.Position+UDim2.new(0,0,-20,0),TextTransparency=1} local tw=TweenService:Create(eff,i,goal) tw:Play(); tw.Completed:Connect(function() eff:Destroy() end) end
local function upd() if sg.Enabled then local t=tot() local r1,nr,d=getRank(t) tl.Text="⚔ Total Stats: "..t; rl.Text="⭐ Rank: "..r1; nrl.Text="↓ Next Rank: "..nr.." ("..d..")"; local diff=math.floor(t)-math.floor(pt) if diff>=1 then playE(tl); showInc(tl,diff) end; pt=t; for _,s in ipairs(stats) do local v=getVal(s) local cr,rr,nd=getRank(v) rows[s].main.Text=icons[s].." "..v.." ("..cr..")"; rows[s].sub.Text="("..nd..") > "..rr; if v>ps[s] then playE(rows[s].main); playE(rows[s].sub); showInc(rows[s].main,v-ps[s]) end; ps[s]=v end end end
local function lis() local h=pg:WaitForChild("HUD"):WaitForChild("Tabs"):WaitForChild("StatsChecker"); for _,s in ipairs(stats) do local f=h:FindFirstChild(s) if f and f:FindFirstChild("AMT") then f.AMT:GetPropertyChangedSignal("Text"):Connect(upd) end end end
local vis=false; local function tog() vis=not vis; if vis then sg.Enabled=true; mf.Position=UDim2.new(0,-400,0,20); local tw=TweenService:Create(mf,TweenInfo.new(0.5,Enum.EasingStyle.Back,Enum.EasingDirection.Out),{Position=UDim2.new(0,20,0,20)}) tw:Play(); upd() else local tw=TweenService:Create(mf,TweenInfo.new(0.5,Enum.EasingStyle.Back,Enum.EasingDirection.In),{Position=UDim2.new(0,-400,0,20)}) tw:Play(); tw.Completed:Connect(function() sg.Enabled=false end) end end
UserInputService.InputBegan:Connect(function(i,p) if not p and i.KeyCode==Enum.KeyCode.K then tog() end end)
lis()
